import type { Metadata } from "next";

import "./globals.css";
import Link from "next/link";
import localFont from 'next/font/local'
import { ThemeProvider } from "@/components/theme-provider"
import { ThemeToggle } from "@/components/theme-toggle";
import DisabledLink from "@/components/ui/DisabledLink";
import { Inter } from "next/font/google";

export const metadata: Metadata = {
  title: "ZINE MAKER 9000",
  description: "Generated by create next app",
};

// Font files can be colocated inside of `app`
const triodion = localFont({
  src: '../Triodion-Regular.ttf',
  display: 'swap',
  variable: '--font-triodion',
})

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${inter.variable} ${triodion.variable}`} suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem
          disableTransitionOnChange
        >


          <div className="grid grid-cols-2 grid-rows-3 gap-0"> {/* Grid container */}

            <div className="dark:text-emerald-400 uppercase font-serif text-xl cursor-default select-none border-2">
              {/* Title */}
              zine maker 9000
            </div>


            <div className="space-x-4 border-2">
              {/* Top navigation */}
              <Link href="/">Create</Link>
              <DisabledLink >Explore</DisabledLink>
              <DisabledLink>Export</DisabledLink>
              <DisabledLink>Print</DisabledLink>

              <ThemeToggle />
            </div>

            <div className="flex flex-col border-2">
              {/* Side navigation */}
              <DisabledLink>About</DisabledLink>
              <DisabledLink>Sign in</DisabledLink>
              <DisabledLink>Updates</DisabledLink>
            </div>

            <div className="col-start-1 row-start-3 border-2">
              {/* Side page */}
              4
            </div>

            <div className="row-span-2 col-start-2 row-start-2 border-2">
              {/* Main content */}
              {children}
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
