import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "ZINE MAKER 9000",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <nav className="relative">
          {/* Top Row */}
          <div className="absolute top-0 left-0 right-0 flex items-center p-4 border-b border-gray-200 bg-white z-10">
            <Link href="/" className="text-lg font-bold mr-32">
              Zine Maker 9000
            </Link>
            <div className="flex gap-4">
              <Link href="#">About</Link>
              <Link href="#">Changelog</Link>
            </div>
          </div>

          {/* Left Column */}
          <div className="absolute top-16 left-0 p-4 border-r">
            <div className="grid grid-cols-1 gap-2">
              <div className="text-gray-500 lowercase">
                An interactive zine maker
              </div>
              <Link href="#">Create</Link>
              <Link href="#">Explore</Link>
              <Link href="#">Export</Link>
              <Link href="#">Print</Link>
            </div>
          </div>
        </nav>
        <div className="pt-32">{children}</div>
      </body>
    </html>
  );
}
